#!/usr/bin/env python3
"""
gen_inventory.py — Generate ansible/hosts.ini from Terraform output.

Run from the repository root after `terraform apply`:

    python3 scripts/gen_inventory.py

Overwrites ansible/hosts.ini in place. Do not hand-edit hosts.ini; it is
owned by this script. Edit this file if static vars (LNET IPs, labels) need
updating, or update terraform/variables.tf if management IPs change.
"""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
TERRAFORM_DIR = REPO_ROOT / "terraform"
INVENTORY_PATH = REPO_ROOT / "ansible" / "hosts.ini"

HEADER = """\
# hosts.ini — generated by scripts/gen_inventory.py
# Do not edit by hand; re-run the script after any `terraform apply`.
#
# ansible_host: management IP from Terraform output (lustre-mgmt NAT network).
# ip_lnet0 / ip_lnet1: static LNET IPs on the lustre-lnet0/lnet1 networks; configured by
#   Ansible via nmcli. Values match the default LNET address scheme; update
#   scripts/gen_inventory.py if you have overridden the LNET address scheme.
"""


def get_management_ips():
    try:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=TERRAFORM_DIR,
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"ERROR: `terraform output` failed:\n{e.stderr}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print("ERROR: terraform not found in PATH.", file=sys.stderr)
        sys.exit(1)

    try:
        outputs = json.loads(result.stdout)
        return outputs["management_ips"]["value"]
    except (json.JSONDecodeError, KeyError) as e:
        print(f"ERROR: could not parse terraform output: {e}", file=sys.stderr)
        sys.exit(1)


def render_inventory(ips):
    return f"""\
{HEADER}
[mgmt_servers]
mgs ansible_host={ips['mgs']} ip_lnet0=192.168.100.9/24 ip_lnet1=192.168.101.9/24 fslabel="MGS" mntpath="mgs"

[metadata_servers]
mds1 ansible_host={ips['mds1']} ip_lnet0=192.168.100.11/24 ip_lnet1=192.168.101.11/24 mdt_index=0 fslabel="lustrefs-MDT0000" mntpath="mdt"
mds2 ansible_host={ips['mds2']} ip_lnet0=192.168.100.13/24 ip_lnet1=192.168.101.13/24 mdt_index=1 fslabel="lustrefs-MDT0001" mntpath="mdt"

[object_servers]
oss1 ansible_host={ips['oss1']} ip_lnet0=192.168.100.15/24 ip_lnet1=192.168.101.15/24 ost_index=0 fslabel="lustrefs-OST0000" mntpath="ost"
oss2 ansible_host={ips['oss2']} ip_lnet0=192.168.100.17/24 ip_lnet1=192.168.101.17/24 ost_index=1 fslabel="lustrefs-OST0001" mntpath="ost"
oss3 ansible_host={ips['oss3']} ip_lnet0=192.168.100.19/24 ip_lnet1=192.168.101.19/24 ost_index=2 fslabel="lustrefs-OST0002" mntpath="ost"
oss4 ansible_host={ips['oss4']} ip_lnet0=192.168.100.21/24 ip_lnet1=192.168.101.21/24 ost_index=3 fslabel="lustrefs-OST0003" mntpath="ost"

[clients]
client1 ansible_host={ips['client1']} ip_lnet0=192.168.100.7/24 ip_lnet1=192.168.101.7/24

[servers:children]
mgmt_servers
metadata_servers
object_servers

[lustre_cluster:children]
servers
clients

[lustre_cluster:vars]
# ansible_user and mgs_enp*_ip are set in group_vars/all.yml
# ansible_ssh_private_key_file=~/.ssh/id_ed25519
"""


def scrub_known_hosts(ips):
    """Remove stale known_hosts entries for all management IPs.

    After terraform destroy + apply the VMs get new host keys.  Leaving
    old entries causes SSH to refuse the connection with a host-key-changed
    error, which breaks both manual SSH and tools that don't suppress
    host-key checking.  ssh-keygen -R is idempotent: it silently does
    nothing when the entry is absent.
    """
    for name, ip in ips.items():
        result = subprocess.run(
            ["ssh-keygen", "-R", ip],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(
                f"WARNING: ssh-keygen -R {ip} ({name}) failed: {result.stderr}",
                file=sys.stderr,
            )
        else:
            print(f"Scrubbed known_hosts: {ip} ({name})")


def main():
    ips = get_management_ips()
    scrub_known_hosts(ips)
    inventory = render_inventory(ips)
    INVENTORY_PATH.write_text(inventory)
    print(f"Written: {INVENTORY_PATH}")


if __name__ == "__main__":
    main()
