---
- name: Lustre Networking Setup
  hosts: lustre_cluster
  become: true  # Runs commands with sudo
  tasks:
    - name: Setup lnet conf file
      ansible.builtin.copy:
        dest: /etc/modprobe.d/lnet.conf
        content: "options lnet networks=tcp0({{ lnet_iface_0 }},{{ lnet_iface_1 }})\n"
        owner: root
        group: root
        mode: '0644'

    - name: Setup nmcli connections for LNET
      community.general.nmcli:
        conn_name: "{{ item.conn }}"
        ifname: "{{ item.iface }}"
        type: ethernet
        ip4: "{{ item.ip }}"
        method4: manual
        state: present
        autoconnect: true
      loop:
        - {conn: "lustre-net0", iface: "{{ lnet_iface_0 }}", ip: "{{ ip_lnet0 }}"}
        - {conn: "lustre-net1", iface: "{{ lnet_iface_1 }}", ip: "{{ ip_lnet1 }}"}
      register: nm_output

    - name: Bring up connections if changed
      ansible.builtin.command: "nmcli connection up {{ item.item.conn }}"
      loop: "{{ nm_output.results }}"
      when: item.changed

    - name: Check if lnet is loaded
      ansible.builtin.shell: lsmod | grep -q "^lnet"
      register: lnet_loaded
      failed_when: false
      changed_when: false

    - name: Load Lnet module
      community.general.modprobe:
        name: lnet
        state: present
      when: lnet_loaded.rc != 0

    - name: Check if LNet is already configured
      # 'lnetctl net show' returns only the loopback (lo) if unconfigured
      ansible.builtin.shell: lctl list_nids | grep -v "0@lo"
      register: lnet_check
      failed_when: false
      changed_when: false

    - name: Initialize LNet stack
      ansible.builtin.command: lnetctl lnet configure --all
      when: lnet_check.stdout == ""

    - name: Check current LNet interfaces
      ansible.builtin.command: lnetctl net show
      register: lnet_show
      changed_when: false

    - name: Add LNET interfaces if missing
      ansible.builtin.command: "lnetctl net add --net tcp --if {{ item }}"
      loop:
        - "{{ lnet_iface_0 }}"
        - "{{ lnet_iface_1 }}"
      # Only run if the interface isn't already in the 'net show' output
      when: item not in lnet_show.stdout

    - name: Ensure Lustre network interfaces persist on boot
      community.general.nmcli:
        conn_name: "{{ item }}"
        autoconnect: true
        state: present
      loop:
        - "lustre-net0"
        - "lustre-net1"

    - name: Create Lustre modules systemd service
      ansible.builtin.template:
        src: lustre-modules.service.j2
        dest: /etc/systemd/system/lustre-modules.service
        owner: root
        group: root
        mode: '0644'
      notify: reload systemd

    - name: Ensure lustre-modules service is enabled
      ansible.builtin.systemd:
        name: lustre-modules
        enabled: true
        state: started  # Runs the modprobes immediately if not already loaded

    - name: Ping MGS from all nodes, lnet0
      ansible.builtin.command: "lctl ping {{ mgs_lnet0_ip }}@tcp"
      register: ping_result
      changed_when: false

    - name: Ping MGS from all nodes, lnet1
      ansible.builtin.command: "lctl ping {{ mgs_lnet1_ip }}@tcp"
      register: ping_result
      changed_when: false

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

#    - name: Verify connection (Ping)
#      ansible.builtin.ping:

#    - name: Get OS version
#      ansible.builtin.debug:
#        msg: "This host is running {{ ansible_distribution }}\
#             {{ ansible_distribution_version }}"

#    - name: Update all packages (Optional)
#      ansible.builtin.dnf:
#        name: "*"
#        state: latest
#        update_cache: true
...
